#!/bin/bash

# Table with all our known/supported GPU cards.
# This table gets used to detect the GPU from lspci output, so add
# your local cards here to get them detected.
declare -g -A CUDA_CARDDB
CUDA_CARDDB['10de:1b80']="GP104 [GeForce GTX 1080]"
CUDA_CARDDB['10de:10ef']="GP102 [GeForce GTX 1080 Ti]"
CUDA_CARDDB['10de:1b06']="GP102 [GeForce GTX 1080 Ti]"
CUDA_CARDDB['10de:1b02']="GP102 [TITAN Xp]"
CUDA_CARDDB['10de:1e02']="TU102 [TITAN RTX]"
CUDA_CARDDB['10de:1e04']="TU102 [GeForce RTX 2080 Ti]"
CUDA_CARDDB['10de:2204']="GA102 [GeForce RTX 3090]"
CUDA_CARDDB['10de:1eb1']="TU104GL [Quadro RTX 4000]"
CUDA_CARDDB['10de:2230']="GA102GL [RTX A6000]"
CUDA_CARDDB['10de:15f7']="GP100GL [Tesla P100 PCIe 12GB]"
CUDA_CARDDB['10de:1db1']="GV100GL [Tesla V100 SXM2 16GB]"
CUDA_CARDDB['10de:1db5']="GV100GL [Tesla V100 SXM2 32GB]"
CUDA_CARDDB['10de:1db8']="GV100GL [Tesla V100 SXM3 32GB]"
CUDA_CARDDB['10de:2235']="GA102GL [A40]"
CUDA_CARDDB['10de:20b0']="GA100 [A100 SXM4 40GB]"
CUDA_CARDDB['10de:20b2']="GA100 [A100 SXM4 80GB]"
CUDA_CARDDB['10de:1bb1']="GP104GL [Quadro P4000]"
export CUDA_CARDDB

